-- Membuat 47 tabel dengan kolom yang diinginkan
-- ===============================================================================ACC OPS ROOM==================
-- Tabel cwp1
CREATE TABLE cwp1 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp2
CREATE TABLE cwp2 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);

-- Tabel cwp3
CREATE TABLE cwp3 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp4
CREATE TABLE cwp4 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp5
CREATE TABLE cwp5 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp6
CREATE TABLE cwp6 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp7
CREATE TABLE cwp7 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);

-- Tabel cwp8
CREATE TABLE cwp8 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp9
CREATE TABLE cwp9 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp10
CREATE TABLE cwp10 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp11
CREATE TABLE cwp11 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp12
CREATE TABLE cwp12 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp13
CREATE TABLE cwp13 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp14
CREATE TABLE cwp14 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp15
CREATE TABLE cwp15 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp16
CREATE TABLE cwp16 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp17
CREATE TABLE cwp17 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp18
CREATE TABLE cwp18 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp19
CREATE TABLE cwp19 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp20
CREATE TABLE cwp20 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp21
CREATE TABLE cwp21 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp22
CREATE TABLE cwp22 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp23
CREATE TABLE cwp23 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp24
CREATE TABLE cwp24 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp25
CREATE TABLE cwp25 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp26
CREATE TABLE cwp26 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp27
CREATE TABLE cwp27 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp28
CREATE TABLE cwp28 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp29
CREATE TABLE cwp29 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- ===============================================================================APP OPS ROOM==================
-- Tabel cwp30
CREATE TABLE cwp30 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp31
CREATE TABLE cwp31 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp32
CREATE TABLE cwp32 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);

-- Tabel cwp33
CREATE TABLE cwp33 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp34
CREATE TABLE cwp34 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp35
CREATE TABLE cwp35 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);

-- Tabel cwp36
CREATE TABLE cwp36 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp37
CREATE TABLE cwp37 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp38
CREATE TABLE cwp38 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);

-- Tabel cwp39
CREATE TABLE cwp39 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp30
CREATE TABLE cwp40 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp41
CREATE TABLE cwp41 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);

-- Tabel cwp42
CREATE TABLE cwp42 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp43
CREATE TABLE cwp43 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp44
CREATE TABLE cwp44 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);

-- ===============================================================================ADC TOWER ROOM==================

-- Tabel cwp45
CREATE TABLE cwp45 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp46
CREATE TABLE cwp46 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);
-- Tabel cwp47
CREATE TABLE cwp47 (
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paper_Level` VARCHAR(10) DEFAULT NULL
);